### ISSUE TITLE
oled display

### ISSUE THREAD

**Issue by patzik** [arananet/Tapuino-Reloaded#2]
Maybe not really an issue, but more a question. You say "17/02/2018: Add a screen voltage selector, this is because some chinese oled screen came with the VCC and GND mixed. This can be change on the screen (there are two resistros to swap voltage) but it will more fast to select onboard with two new available solder jumpers."
I still have some pcb's with the 0.2 design and some screens with the swapped vcc/gnd, how can I swap these pins on the screen, which 2 resistors need to be changed?
This was in the tzxduino pcb not the tapuino..

**Comment by arananet** [comment]
Hi,On the back of the oled screen there are on the top of the pcb just down to the pins connection, two 0ohm resistors. You need to swap or remove them and put a bridge with solder iron on the path to swap the voltages.I dont remember correctly but for example1  2  3 (2-3 soldered by default)1  2  3 (1-2 soldered by default)And it must be 1  2  3 (1-2 soldered by default)1  2  3 (2-3 soldered by default)Regards,Edu.

  El 5 de marzo de 2018 a las 0:40 patzik <notifications@github.com> escribió:
 
 
 Maybe not really an issue, but more a question. You say "17/02/2018: Add a screen voltage selector, this is because some chinese oled screen came with the VCC and GND mixed. This can be change on the screen (there are two resistros to swap voltage) but it will more fast to select onboard with two new available solder jumpers." I still have some pcb's with the 0.2 design and some screens with the swapped vcc/gnd, how can I swap these pins on the screen, which 2 resistors need to be changed?

**Comment by patzik** [comment]
I guess I have different screens, there are no 0-Ohm resistors and gnd is connected directly to the ground plane.

I have another question, when I enable the op-amp, there is no sound from the tzxduino, also the led ‘active’ is not working as expected. When placed as indicated on the pcb is does not light up, when placed reversed it lights continuously.
Only thing I’m not sure about is the ‘orientation’ of the 4050D because I don’t see a dot or notch on the ic.
Any suggestions? Could it be the 4050D?

**Comment by arananet** [comment]
Do you have the last version of the tzxduino? the old version has the "enable amp" backwards.

![schema](https://user-images.githubusercontent.com/6855780/37040716-c09624e2-215a-11e8-81dc-900741ce46e8.png)

4050D pin is the top left (note that blue footprint is the bottom layer).

Led pins are marked correctly at least on the last version.

Let me know if you sort out.

Regards,
Edu.

**Comment by patzik** [comment]
![img_1291](https://user-images.githubusercontent.com/32332590/37057657-5d8c8a5c-2188-11e8-888e-637b8269878c.jpg)
The board I am using is 1.31 and the tzxduino version is 1.9.
Regarding the 4050D orientation, I didn't mean the silkscreen but the actual component (picture included). I just tried turning the component 180 degrees, but this sent me into a wild goose chase, won't bore you with the details but I switched it back to the orientation as in the picture (not 100% sure still if it is ok, but I guess the whole thing wouldn't work if it wasn't)
Can you clarify the usage of the solder jumper on the back and the jumper on the front, do I need to use/set both or are they the same?

**Comment by arananet** [comment]
Hi, 

4050D is ok on that pic. 

Solder jumper on the back is for enable or disable the amp, by the amp i mean by tell tzxduino that "have an existing amp" or not, which include all the electronics of the amplification.

I have deleted the version 1.3.1 from my repository, so I don't remember correctly. But there was a mistake on the silkscreen. With the enable and disable amp. If you 1.31 has a dual jumper in the front, then you have to set the configuration of your oled screen acording to your physical setup.

Example:

Top jumper: Solder VCC to out1 to select VCC on the left connector.
Bottom jumper: Solder GND to out2 to select GND on the left connector.

So the screen connector would be VCC GND SCL SDA

Note: That if your oled screen puts SCK instead of SCL you maybe need pullups resistors in order to make it work. Some oled has already, some others don't

BTW. I see you have put an issue in a wrong repository. This repo is for the TAPUINO not for the TZXDUINO.

Regards,
Edu.
